<?php
/** This file is part of TKSocioMenu Widget Plugin project
 *
 *      @desc TKSocioMenu Widget class
 *   @package TKSocioMenu
 *   @version 0.1a
 *    @author Ravil Sarvaritdinov <ra9oaj@gmail.com>
 * @copyright 2017 KCFinder Project
 *   @license http://opensource.org/licenses/GPL-3.0 GPLv3
 *   @license http://opensource.org/licenses/LGPL-3.0 LGPLv3
 *      @link https://github.com/tehnokom/alfo-tk-socio-menu-plugin
 */

class TK_Socio_Menu extends WP_Widget
{
  public function __construct()
  {
      $options = array('classname' => 'TK_Socio_Menu',
          'description' => __('The widget allows you to add menus to the social profile of the user', 'tkgp'));
      parent::__construct('tk_socio_menu', 'TK Socio Menu Widget', $options);
  }

  static function register_widget()
  {
      register_widget('TK_Socio_Menu');
  }

  public function form($instance)
  {
      echo 'Hello!';
  }

  public function update($new_instance, $old_instance)
  {
      return parent::update($new_instance, $old_instance); // TODO: Change the autogenerated stub
  }

  public function widget($args, $instance)
  {
      if(is_user_logged_in() && defined('BP_PLUGIN_DIR')) {
          add_action('get_footer', array($this, 'load_js_css'));

          require_once (TK_SM_TEMPLATES_ROOT . 'default/menu.php');
      }
  }

  public function load_js_css()
  {
      wp_register_style('tk_sm_template_css', TK_SM_TEMPLATES_URL . 'default/css/style.css');
      wp_enqueue_style('tk_sm_template_css');

      wp_register_script('tk_sm_template_js', TK_SM_TEMPLATES_URL . 'default/js/ui.js', array('jquery'));
      wp_enqueue_script('tk_sm_template_js');
  }
};